; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24213.1 

	TITLE	G:\DOOM\New Kingdom\Game Development [torrents.ru]\AI\Programming Game AI by Example\Buckland_AISource\Buckland_Chapter7 to 10_Raven\goals\Goal_SayPhrase.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
